services:
  rabbitmq-node-1:
    container_name: rabbitmq-node-1
    image: rabbitmq:3.12-management
    hostname: rabbitmq-node-1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
      - RABBITMQ_PLUGINS=rabbitmq_management rabbitmq_federation rabbitmq_federation_management
    volumes:
      - ./volumes/rabbitmq-node-1:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - rabbitmq_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  rabbitmq-node-2:
    container_name: rabbitmq-node-2
    image: rabbitmq:3.12-management
    hostname: rabbitmq-node-2
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit@rabbitmq-node-1
    volumes:
      - ./volumes/rabbitmq-node-2:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./config/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh:ro
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq-node-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq-node-3:
    container_name: rabbitmq-node-3
    image: rabbitmq:3.12-management
    hostname: rabbitmq-node-3
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
      - CLUSTERED=true
      - CLUSTER_WITH=rabbit@rabbitmq-node-1
    volumes:
      - ./volumes/rabbitmq-node-3:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./config/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh:ro
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq-node-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  setup-policy:
    container_name: setup-policy
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq-node-1:
        condition: service_healthy
      rabbitmq-node-2:
        condition: service_healthy
      rabbitmq-node-3:
        condition: service_healthy
    volumes:
      - ./config/setup-policy.sh:/setup-policy.sh:ro
    entrypoint: /bin/bash
    command: /setup-policy.sh
    restart: on-failure

networks:
  rabbitmq_network:
    driver: bridge
