version: '3.8'

services:
  rabbitmq-node-1:
    container_name: rabbitmq-node-1
    image: rabbitmq:3.12-management
    hostname: rabbitmq-node-1
    ports:
      - "${RABBITMQ_DOCKER_HOST_PORT:-5672}:5672"
      - "${RABBITMQ_DOCKER_UI_PORT:-15672}:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
    volumes:
      - ./volumes/rabbitmq-node-1:/var/lib/rabbitmq
      - ./rabbitmq/config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/config/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - rabbitmq_network

  rabbitmq-node-2:
    container_name: rabbitmq-node-2
    image: rabbitmq:3.12-management
    hostname: rabbitmq-node-2
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
    volumes:
      - ./volumes/rabbitmq-node-2:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq-node-1

  rabbitmq-node-3:
    container_name: rabbitmq-node-3
    image: rabbitmq:3.12-management
    hostname: rabbitmq-node-3
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-SWQOKODSQALRPCLNMEQG}
    volumes:
      - ./volumes/rabbitmq-node-3:/var/lib/rabbitmq
    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq-node-1

networks:
  rabbitmq_network:
    driver: bridge